//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.Ocl
{
   public static partial class OclInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     [return: MarshalAs(CvInvoke.BoolMarshalType)]
     internal static extern bool cveOclKernelEmpty(IntPtr obj);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern IntPtr cveOclKernelNativeKernelPtr(IntPtr obj);
     
   }

   public partial class Kernel
   {

     /// <summary>
     /// Indicates if the kernel is empty
     /// </summary>
     public bool Empty
     {
        get { return OclInvoke.cveOclKernelEmpty(_ptr); } 
     }
     
     /// <summary>
     /// The pointer to the native kernel
     /// </summary>
     public IntPtr NativeKernelPtr
     {
        get { return OclInvoke.cveOclKernelNativeKernelPtr(_ptr); } 
     }
     
   }
}