//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV
{
   public static partial class CvInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     [return: MarshalAs(CvInvoke.BoolMarshalType)]
     internal static extern bool cveVideoCaptureIsOpened(IntPtr obj);
     
   }

   public partial class VideoCapture
   {

     /// <summary>
     /// True if the camera is opened
     /// </summary>
     public bool IsOpened
     {
        get { return CvInvoke.cveVideoCaptureIsOpened(_ptr); } 
     }
     
   }
}