//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV
{
   public static partial class CvInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     [return: MarshalAs(CvInvoke.BoolMarshalType)]
     internal static extern bool cveOutputArrayFixedSize(IntPtr obj);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     [return: MarshalAs(CvInvoke.BoolMarshalType)]
     internal static extern bool cveOutputArrayFixedType(IntPtr obj);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     [return: MarshalAs(CvInvoke.BoolMarshalType)]
     internal static extern bool cveOutputArrayNeeded(IntPtr obj);
     
   }

   public partial class OutputArray
   {

     /// <summary>
     /// True if the output array is fixed size
     /// </summary>
     public bool FixedSize
     {
        get { return CvInvoke.cveOutputArrayFixedSize(_ptr); } 
     }
     
     /// <summary>
     /// True if the output array is fixed type
     /// </summary>
     public bool FixedType
     {
        get { return CvInvoke.cveOutputArrayFixedType(_ptr); } 
     }
     
     /// <summary>
     /// True if the output array is needed
     /// </summary>
     public bool Needed
     {
        get { return CvInvoke.cveOutputArrayNeeded(_ptr); } 
     }
     
   }
}