//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.Stitching
{
   public static partial class StitchingInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern double cveStitcherWorkScale(IntPtr obj);
     
   }

   public partial class Stitcher
   {

     /// <summary>
     /// The work scale
     /// </summary>
     public double WorkScale
     {
        get { return StitchingInvoke.cveStitcherWorkScale(_ptr); } 
     }
     
   }
}